"""
D-3 Glossary verbatim data (Part 3: P-Z).
"""

GLOSSARY_PART3 = [
    # ── P ─────────────────────────────────────────────────────────────────
    {"term": "peer review", "page": 448,
     "definition": "The review of work products performed by peers during the development of work products to identify defects for removal.",
     "cross_references": ["work product"],
     "notes": "The term 'peer review' is used in the CMMI Product Suite instead of the term 'work product inspection.'"},
    {"term": "performance parameters", "page": 448,
     "definition": "The measures of effectiveness and other key measures used to guide and control progressive development."},
    {"term": "performed process", "page": 448,
     "definition": "A process that accomplishes the needed work to produce work products; the specific goals of the process area are satisfied."},
    {"term": "planned process", "page": 448,
     "definition": "A process that is documented by both a description and a plan.",
     "notes": "The description and plan should be coordinated and the plan should include standards, requirements, objectives, resources, and assignments."},
    {"term": "policy", "page": 448,
     "definition": "See organizational policy.",
     "cross_references": ["organizational policy"]},
    {"term": "process", "page": 448,
     "definition": "A set of interrelated activities, which transform inputs into outputs, to achieve a given purpose.",
     "cross_references": ["process area", "subprocess", "process element"],
     "notes": "There is a special use of the phrase 'the process' in the statements and descriptions of the generic goals and generic practices. 'The process,' as used in Part Two, is the process or processes that implement the process area. The terms 'process,' 'subprocess' and 'process element' form a hierarchy with 'process' as the highest, most general term, 'subprocesses' below it, and 'process element' as the most specific. This definition of process is consistent with the definition of process in ISO 9000, ISO 12207, ISO 15504, and EIA 731."},
    {"term": "process action plan", "page": 448,
     "definition": "A plan, usually resulting from appraisals, that documents how specific improvements targeting the weaknesses uncovered by an appraisal will be implemented."},
    {"term": "process action team", "page": 448,
     "definition": "A team that has the responsibility to develop and implement process improvement activities for an organization as documented in a process action plan."},
    {"term": "process and technology improvements", "page": 448,
     "definition": "Incremental and innovative improvements to processes and to process, product, or service technologies."},
    {"term": "process architecture", "page": 449,
     "definition": "(1) The ordering, interfaces, interdependencies, and other relationships among the process elements in a standard process, or (2) the interfaces, interdependencies, and other relationships between process elements and external processes."},
    {"term": "process area", "abbreviation": "PA", "page": 449,
     "definition": "A cluster of related practices in an area that, when implemented collectively, satisfies a set of goals considered important for making improvement in that area."},
    {"term": "process asset", "page": 449,
     "definition": "Anything the organization considers useful in attaining the goals of a process area.",
     "cross_references": ["organizational process assets"]},
    {"term": "process asset library", "page": 449,
     "definition": "A collection of process asset holdings that can be used by an organization, project, or work group.",
     "cross_references": ["organization's process asset library"]},
    {"term": "process attribute", "page": 449,
     "definition": "A measurable characteristic of process capability applicable to any process."},
    {"term": "process capability", "page": 449,
     "definition": "The range of expected results that can be achieved by following a process."},
    {"term": "process definition", "page": 449,
     "definition": "The act of defining and describing a process.",
     "cross_references": ["process description"],
     "notes": "The result of process definition is a process description."},
    {"term": "process description", "page": 449,
     "definition": "A documented expression of a set of activities performed to achieve a given purpose.",
     "notes": "A process description provides an operational definition of the major components of a process. The description specifies, in a complete, precise, and verifiable manner, the requirements, design, behavior, or other characteristics of a process. It also can include procedures for determining whether these provisions have been satisfied. Process descriptions can be found at the activity, project, work group, or organizational level."},
    {"term": "process element", "page": 450,
     "definition": "The fundamental unit of a process.",
     "cross_references": ["process", "subprocess"],
     "notes": "A process can be defined in terms of subprocesses or process elements. A subprocess is a process element when it is not further decomposed into subprocesses or process elements. Each process element covers a closely related set of activities (e.g., estimating element, peer review element). Process elements can be portrayed using templates to be completed, abstractions to be refined, or descriptions to be modified or used. A process element can be an activity or task. The terms 'process,' 'subprocess,' and 'process element' form a hierarchy with 'process' as the highest, most general term, 'subprocesses' below it, and 'process element' as the most specific."},
    {"term": "process group", "page": 450,
     "definition": "A collection of specialists who facilitate the definition, maintenance, and improvement of processes used by the organization."},
    {"term": "process improvement", "page": 450,
     "definition": "A program of activities designed to improve the process performance and maturity of the organization's processes, and the results of such a program."},
    {"term": "process improvement objectives", "page": 450,
     "definition": "A set of target characteristics established to guide the effort to improve an existing process in a specific, measurable way either in terms of resultant product or service characteristics (e.g., quality, product performance, conformance to standards) or in the way in which the process is executed (e.g., elimination of redundant process steps, combination of process steps, improvement of cycle time).",
     "cross_references": ["organization's business objectives", "quantitative objective"]},
    {"term": "process improvement plan", "page": 450,
     "definition": "A plan for achieving organizational process improvement objectives based on a thorough understanding of current strengths and weaknesses of the organization's processes and process assets."},
    {"term": "process measurement", "page": 450,
     "definition": "A set of operations used to determine values of measures of a process and its resulting products or services for the purpose of characterizing and understanding the process.",
     "cross_references": ["measurement"]},
    {"term": "process owner", "page": 451,
     "definition": "The person (or team) responsible for defining and maintaining a process.",
     "cross_references": ["defined process", "standard process"],
     "notes": "At the organizational level, the process owner is the person (or team) responsible for the description of a standard process; at the project or work group level, the process owner is the person (or team) responsible for the description of the defined process. A process can therefore have multiple owners at different levels of responsibility."},
    {"term": "process performance", "page": 451,
     "definition": "A measure of results achieved by following a process.",
     "cross_references": ["measure (noun)"],
     "notes": "Process performance is characterized by both process measures (e.g., effort, cycle time, defect removal efficiency) and product or service measures (e.g., reliability, defect density, response time)."},
    {"term": "process performance baseline", "page": 451,
     "definition": "A documented characterization of process performance, which can include central tendency and variation.",
     "cross_references": ["process performance"],
     "notes": "A process performance baseline can be used as a benchmark for comparing actual process performance against expected process performance."},
    {"term": "process performance model", "page": 451,
     "definition": "A description of relationships among the measurable attributes of one or more processes or work products that is developed from historical process performance data and is used to predict future performance.",
     "cross_references": ["measure (noun)"]},
    {"term": "process tailoring", "page": 451,
     "definition": "Making, altering, or adapting a process description for a particular end.",
     "cross_references": ["defined process", "organization's set of standard processes", "process description"]},
    {"term": "product", "page": 452,
     "definition": "A work product that is intended for delivery to a customer or end user.",
     "cross_references": ["customer", "product component", "service", "work product"],
     "notes": "This term has a special meaning in the CMMI Product Suite besides its common standard English meaning. The form of a product can vary in different contexts."},
    {"term": "product baseline", "page": 452,
     "definition": "The initial approved technical data package defining a configuration item during the production, operation, maintenance, and logistic support of its lifecycle.",
     "cross_references": ["configuration item", "configuration management", "technical data package"]},
    {"term": "product component", "page": 452,
     "definition": "A work product that is a lower level component of the product.",
     "cross_references": ["product", "work product"],
     "notes": "Product components are integrated to produce the product. There can be multiple levels of product components. Throughout the process areas, where the terms 'product' and 'product component' are used, their intended meanings also encompass services, service systems, and their components."},
    {"term": "product component requirements", "page": 452,
     "definition": "A complete specification of a product or service component, including fit, form, function, performance, and any other requirement."},
    {"term": "product lifecycle", "page": 452,
     "definition": "The period of time, consisting of phases, that begins when a product or service is conceived and ends when the product or service is no longer available for use.",
     "notes": "A product lifecycle could consist of the following phases: (1) concept and vision, (2) feasibility, (3) design/development, (4) production, and (5) phase out."},
    {"term": "product line", "page": 453,
     "definition": "A group of products sharing a common, managed set of features that satisfy specific needs of a selected market or mission and that are developed from a common set of core assets in a prescribed way.",
     "cross_references": ["service line"]},
    {"term": "product related lifecycle processes", "page": 453,
     "definition": "Processes associated with a product or service throughout one or more phases of its life (e.g., from conception through disposal), such as manufacturing and support processes."},
    {"term": "product requirements", "page": 453,
     "definition": "A refinement of customer requirements into the developers' language, making implicit requirements into explicit derived requirements.",
     "cross_references": ["derived requirements", "product component requirements"]},
    {"term": "product suite", "page": 453,
     "definition": "See CMMI Product Suite.",
     "cross_references": ["CMMI Product Suite"]},
    {"term": "project", "page": 453,
     "definition": "A managed set of interrelated activities and resources, including people, that delivers one or more products or services to a customer or end user.",
     "cross_references": ["project startup"],
     "notes": "A project has an intended beginning (i.e., project startup) and end. Projects typically operate according to a plan. In some contexts, the term 'program' is used to refer to a project."},
    {"term": "project plan", "page": 454,
     "definition": "A plan that provides the basis for performing and controlling the project's activities, which addresses the commitments to the project's customer.",
     "notes": "Project planning includes estimating the attributes of work products and tasks, determining the resources needed, negotiating commitments, producing a schedule, and identifying and analyzing project risks."},
    {"term": "project progress and performance", "page": 454,
     "definition": "What a project achieves with respect to implementing project plans, including effort, cost, schedule, and technical performance.",
     "cross_references": ["technical performance"]},
    {"term": "project startup", "page": 454,
     "definition": "When a set of interrelated resources for a project are directed to develop or deliver one or more products or services for a customer or end user.",
     "cross_references": ["project"]},
    {"term": "prototype", "page": 454,
     "definition": "A preliminary type, form, or instance of a product, service, product component, or service component that serves as a model for later stages or for the final, complete version of the product or service.",
     "notes": "This model of the product or service (e.g., physical, electronic, digital, analytical) can be used for the following (and other) purposes: assessing the feasibility of a new or unfamiliar technology, assessing or mitigating technical risk, validating requirements, demonstrating critical features, qualifying a product or service, qualifying a process, characterizing performance or features of the product or service, and elucidating physical principles."},

    # ── Q ─────────────────────────────────────────────────────────────────
    {"term": "quality", "page": 454,
     "definition": "The degree to which a set of inherent characteristics fulfills requirements."},
    {"term": "quality and process performance objectives", "page": 454,
     "definition": "Quantitative objectives and requirements for product quality, service quality, and process performance.",
     "notes": "Quantitative process performance objectives include quality; however, to emphasize the importance of quality in the CMMI Product Suite, the phrase 'quality and process performance objectives' is used. 'Process performance objectives' are referenced in maturity level 3; the term 'quality and process performance objectives' implies the use of quantitative data and is only used in maturity levels 4 and 5."},
    {"term": "quality assurance", "page": 455,
     "definition": "A planned and systematic means for assuring management that the defined standards, practices, procedures, and methods of the process are applied."},
    {"term": "quality attribute", "page": 455,
     "definition": "A property of a product or service by which its quality will be judged by relevant stakeholders. Quality attributes are characterizable by some appropriate measure.",
     "notes": "Quality attributes are non-functional, such as timeliness, throughput, responsiveness, security, modifiability, reliability, and usability. They have a significant influence on the architecture."},
    {"term": "quality control", "page": 455,
     "definition": "The operational techniques and activities that are used to fulfill requirements for quality.",
     "cross_references": ["quality assurance"]},
    {"term": "quantitative management", "page": 455,
     "definition": "Managing a project or work group using statistical and other quantitative techniques to build an understanding of the performance or predicted performance of processes in comparison to the project's or work group's quality and process performance objectives, and identifying corrective action that may need to be taken.",
     "cross_references": ["statistical techniques"]},
    {"term": "quantitative objective", "page": 455,
     "definition": "Desired target value expressed using quantitative measures.",
     "cross_references": ["measure (noun)", "process improvement objectives", "quality and process performance objectives"]},
    {"term": "quantitatively managed", "page": 455,
     "definition": "See quantitative management.",
     "cross_references": ["quantitative management"]},

    # ── R ─────────────────────────────────────────────────────────────────
    {"term": "reference model", "page": 455,
     "definition": "A model that is used as a benchmark for measuring an attribute."},
    {"term": "relevant stakeholder", "page": 455,
     "definition": "A stakeholder that is identified for involvement in specified activities and is included in a plan.",
     "cross_references": ["stakeholder"]},
    {"term": "representation", "page": 455,
     "definition": "The organization, use, and presentation of a CMM's components.",
     "notes": "Overall, two types of approaches to presenting best practices are evident: the staged representation and the continuous representation."},
    {"term": "required CMMI components", "page": 456,
     "definition": "CMMI components that are essential to achieving process improvement in a given process area.",
     "notes": "Specific goals and generic goals are required model components. Goal satisfaction is used in appraisals as the basis for deciding whether a process area has been satisfied."},
    {"term": "requirement", "page": 456,
     "definition": "(1) A condition or capability needed by a user to solve a problem or achieve an objective. (2) A condition or capability that must be met or possessed by a product, service, product component, or service component to satisfy a supplier agreement, standard, specification, or other formally imposed documents. (3) A documented representation of a condition or capability as in (1) or (2).",
     "cross_references": ["supplier agreement"]},
    {"term": "requirements analysis", "page": 456,
     "definition": "The determination of product or service specific functional and quality attribute characteristics based on analyses of customer needs, expectations, and constraints; operational concept; projected utilization environments for people, products, services, and processes; and measures of effectiveness.",
     "cross_references": ["operational concept"]},
    {"term": "requirements elicitation", "page": 456,
     "definition": "Using systematic techniques such as prototypes and structured surveys to proactively identify and document customer and end-user needs."},
    {"term": "requirements management", "page": 456,
     "definition": "The management of all requirements received by or generated by the project or work group, including both technical and nontechnical requirements as well as those requirements levied on the project or work group by the organization.",
     "cross_references": ["nontechnical requirements"]},
    {"term": "requirements traceability", "page": 456,
     "definition": "A discernable association between requirements and related requirements, implementations, and verifications.",
     "cross_references": ["bidirectional traceability", "traceability"]},
    {"term": "return on investment", "abbreviation": "ROI", "page": 456,
     "definition": "The ratio of revenue from output (product or service) to production costs, which determines whether an organization benefits from performing an action to produce something."},
    {"term": "risk analysis", "page": 456,
     "definition": "The evaluation, classification, and prioritization of risks."},
    {"term": "risk identification", "page": 456,
     "definition": "An organized, thorough approach used to seek out probable or realistic risks in achieving objectives."},
    {"term": "risk management", "page": 457,
     "definition": "An organized, analytic process used to identify what might cause harm or loss (identify risks); to assess and quantify the identified risks; and to develop and, if needed, implement an appropriate approach to prevent or handle causes of risk that could result in significant harm or loss.",
     "notes": "Typically, risk management is performed for the activities of a project, a work group, an organization, or other organizational units that are developing or delivering products or services."},

    # ── S ─────────────────────────────────────────────────────────────────
    {"term": "senior manager", "page": 457,
     "definition": "A management role at a high enough level in an organization that the primary focus of the person filling the role is the long-term vitality of the organization rather than short-term concerns and pressures.",
     "cross_references": ["higher level management"],
     "notes": "A senior manager has authority to direct the allocation or reallocation of resources in support of organizational process improvement effectiveness. A senior manager can be any manager who satisfies this description, including the head of the organization."},
    {"term": "service", "page": 457,
     "definition": "A product that is intangible and non-storable.",
     "cross_references": ["product", "customer", "work product"]},
    {"term": "service agreement", "page": 458,
     "definition": "A binding, written record of a promised exchange of value between a service provider and a customer.",
     "cross_references": ["customer"]},
    {"term": "service catalog", "page": 458,
     "definition": "A list or repository of standardized service definitions."},
    {"term": "service incident", "page": 458,
     "definition": "An indication of an actual or potential interference with a service.",
     "notes": "Service incidents can occur in any service domain because customer and end-user complaints are types of incidents."},
    {"term": "service level", "page": 458,
     "definition": "A defined magnitude, degree, or quality of service delivery performance.",
     "cross_references": ["service", "service level measure"]},
    {"term": "service level agreement", "abbreviation": "SLA", "page": 459,
     "definition": "A service agreement that specifies delivered services; service measures; levels of acceptable and unacceptable services; and expected responsibilities, liabilities, and actions of both the provider and customer in anticipated situations.",
     "cross_references": ["measure (noun)", "service", "service agreement"]},
    {"term": "service level measure", "page": 459,
     "definition": "A measure of service delivery performance associated with a service level.",
     "cross_references": ["measure (noun)", "service level"]},
    {"term": "service line", "page": 459,
     "definition": "A consolidated and standardized set of services and service levels that satisfy specific needs of a selected market or mission area.",
     "cross_references": ["product line", "service level"]},
    {"term": "service request", "page": 459,
     "definition": "A communication from a customer or end user that one or more specific instances of service delivery are desired.",
     "cross_references": ["service agreement"]},
    {"term": "service requirements", "page": 459,
     "definition": "The complete set of requirements that affect service delivery and service system development.",
     "cross_references": ["service system"]},
    {"term": "service system", "page": 460,
     "definition": "An integrated and interdependent combination of component resources that satisfies service requirements.",
     "cross_references": ["service system component", "service requirements"]},
    {"term": "service system component", "page": 460,
     "definition": "A resource required for a service system to successfully deliver services.",
     "cross_references": ["customer", "end user"]},
    {"term": "service system consumable", "page": 460,
     "definition": "A service system component that ceases to be available or becomes permanently changed by its use during the delivery of a service."},
    {"term": "shared vision", "page": 461,
     "definition": "A common understanding of guiding principles, including mission, objectives, expected behavior, values, and final outcomes, which are developed and used by a project or work group."},
    {"term": "software engineering", "page": 461,
     "definition": "(1) The application of a systematic, disciplined, quantifiable approach to the development, operation, and maintenance of software. (2) The study of approaches as in (1).",
     "cross_references": ["hardware engineering", "systems engineering"]},
    {"term": "solicitation", "page": 461,
     "definition": "The process of preparing a package to be used in selecting a supplier.",
     "cross_references": ["solicitation package"]},
    {"term": "solicitation package", "page": 461,
     "definition": "A collection of formal documents that includes a description of the desired form of response from a potential supplier, the relevant statement of work for the supplier, and required provisions in the supplier agreement."},
    {"term": "special cause of variation", "page": 461,
     "definition": "A cause of a defect that is specific to some transient circumstance and is not an inherent part of a process.",
     "cross_references": ["common cause of variation"]},
    {"term": "specific goal", "abbreviation": "SG", "page": 461,
     "definition": "A required model component that describes the unique characteristics that must be present to satisfy the process area.",
     "cross_references": ["capability level", "generic goal", "organization's business objectives", "process area"]},
    {"term": "specific practice", "abbreviation": "SP", "page": 461,
     "definition": "An expected model component that is considered important in achieving the associated specific goal.",
     "cross_references": ["process area", "specific goal"],
     "notes": "The specific practices describe the activities expected to result in achievement of the specific goals of a process area."},
    {"term": "stable process", "page": 461,
     "definition": "The state in which special causes of process variation have been removed and prevented from recurring so that only common causes of process variation of the process remain.",
     "cross_references": ["capable process", "common cause of variation", "special cause of variation", "standard process"]},
    {"term": "staged representation", "page": 461,
     "definition": "A model structure wherein attaining the goals of a set of process areas establishes a maturity level; each level builds a foundation for subsequent levels.",
     "cross_references": ["maturity level", "process area"]},
    {"term": "stakeholder", "page": 462,
     "definition": "A group or individual that is affected by or is in some way accountable for the outcome of an undertaking.",
     "cross_references": ["customer", "relevant stakeholder"],
     "notes": "Stakeholders may include project or work group members, suppliers, customers, end users, and others. This term has a special meaning in the CMMI Product Suite besides its common standard English meaning."},
    {"term": "standard (noun)", "page": 462,
     "definition": "Formal requirements developed and used to prescribe consistent approaches to acquisition, development, or service.",
     "notes": "Examples of standards include ISO/IEC standards, IEEE standards, and organizational standards."},
    {"term": "standard process", "page": 462,
     "definition": "An operational definition of the basic process that guides the establishment of a common process in an organization.",
     "cross_references": ["defined process"],
     "notes": "A standard process describes the fundamental process elements that are expected to be incorporated into any defined process. It also describes relationships (e.g., ordering, interfaces) among these process elements."},
    {"term": "statement of work", "abbreviation": "SOW", "page": 462,
     "definition": "A description of work to be performed."},
    {"term": "statistical and other quantitative techniques", "page": 462,
     "definition": "Analytic techniques that enable accomplishing an activity by quantifying parameters of the task (e.g., inputs, size, effort, and performance).",
     "cross_references": ["statistical techniques", "quantitative management"]},
    {"term": "statistical process control", "abbreviation": "SPC", "page": 462,
     "definition": "Statistically based analysis of a process and measures of process performance, which identify common and special causes of variation in process performance and maintain process performance within limits.",
     "cross_references": ["common cause of variation", "special cause of variation", "statistical techniques"]},
    {"term": "statistical techniques", "page": 463,
     "definition": "Techniques adapted from the field of mathematical statistics used for activities such as characterizing process performance, understanding process variation, and predicting outcomes.",
     "notes": "Examples of statistical techniques include sampling techniques, analysis of variance, chi-squared tests, and process control charts."},
    {"term": "subpractice", "page": 463,
     "definition": "An informative model component that provides guidance for interpreting and implementing specific or generic practices.",
     "notes": "Subpractices may be worded as if prescriptive, but they are actually meant only to provide ideas that can be useful for process improvement."},
    {"term": "subprocess", "page": 463,
     "definition": "A process that is part of a larger process.",
     "cross_references": ["process", "process description", "process element"]},
    {"term": "supplier", "page": 463,
     "definition": "(1) An entity delivering products or performing services being acquired. (2) An individual, partnership, company, corporation, association, or other entity having an agreement with an acquirer for the design, development, manufacture, maintenance, modification, or supply of items under the terms of an agreement.",
     "cross_references": ["acquirer"]},
    {"term": "supplier agreement", "page": 463,
     "definition": "A documented agreement between the acquirer and supplier.",
     "cross_references": ["supplier"],
     "notes": "Supplier agreements are also known as contracts, licenses, and memoranda of agreement."},
    {"term": "sustainment", "page": 463,
     "definition": "The processes used to ensure that a product or service remains operational."},
    {"term": "system of systems", "abbreviation": "SoS", "page": 463,
     "definition": "A set or arrangement of systems that results when independent and useful systems are integrated into a large system that delivers unique capabilities."},
    {"term": "systems engineering", "page": 464,
     "definition": "The interdisciplinary approach governing the total technical and managerial effort required to transform a set of customer needs, expectations, and constraints into a solution and to support that solution throughout its life.",
     "cross_references": ["hardware engineering", "software engineering"]},

    # ── T ─────────────────────────────────────────────────────────────────
    {"term": "tailoring", "page": 464,
     "definition": "The act of making, altering, or adapting something for a particular end.",
     "notes": "For example, a project or work group establishes its defined process by tailoring from the organization's set of standard processes to meet its objectives, constraints, and environment. Likewise, a service provider tailors standard services for a particular service agreement."},
    {"term": "tailoring guidelines", "page": 464,
     "definition": "Organizational guidelines that enable projects, work groups, and organizational functions to appropriately adapt standard processes for their use.",
     "notes": "The organization's set of standard processes is described at a general level that may not be directly usable to perform a process. Tailoring guidelines aid those who establish the defined processes for project or work groups. Tailoring guidelines cover (1) selecting a standard process, (2) selecting an approved lifecycle model, and (3) tailoring the selected standard process and lifecycle model to fit project or work group needs."},
    {"term": "target profile", "page": 464,
     "definition": "A list of process areas and their corresponding capability levels that represent an objective for process improvement.",
     "cross_references": ["achievement profile", "capability level profile"],
     "notes": "Target profiles are only available when using the continuous representation."},
    {"term": "target staging", "page": 464,
     "definition": "A sequence of target profiles that describes the path of process improvement to be followed by the organization.",
     "cross_references": ["achievement profile", "capability level profile", "target profile"],
     "notes": "Target staging is only available when using the continuous representation."},
    {"term": "team", "page": 465,
     "definition": "A group of people with complementary skills and expertise who work together to accomplish specified objectives.",
     "notes": "A team establishes and maintains a process that identifies roles, responsibilities, and interfaces; is sufficiently precise to enable the team to measure, manage, and improve their work performance; and enables the team to make and defend their commitments."},
    {"term": "technical data package", "page": 465,
     "definition": "A collection of items that can include the following if such information is appropriate to the type of product and product component: product architecture description, allocated requirements, product component descriptions, product related lifecycle process descriptions (if not described as separate product components), key product characteristics, required physical characteristics and constraints, interface requirements, materials requirements (bills of material and material characteristics), fabrication and manufacturing requirements (for both the original equipment manufacturer and field support), verification criteria used to ensure requirements have been achieved, conditions of use (environments) and operating/usage scenarios, modes and states for operations, support, training, manufacturing, disposal, and verifications throughout the life of the product, rationale for decisions and characteristics (e.g., requirements, requirement allocations, design choices)."},
    {"term": "technical performance", "page": 466,
     "definition": "Characteristic of a process, product, or service, generally defined by a functional or technical requirement.",
     "notes": "Examples of technical performance types include estimating accuracy, end-user functions, security functions, response time, component accuracy, maximum weight, minimum throughput, allowable range."},
    {"term": "technical performance measure", "page": 466,
     "definition": "Precisely defined technical measure of a requirement, capability, or some combination of requirements and capabilities.",
     "cross_references": ["measure (noun)"]},
    {"term": "technical requirements", "page": 466,
     "definition": "Properties (i.e., attributes) of products or services to be acquired or developed."},
    {"term": "traceability", "page": 466,
     "definition": "A discernable association among two or more logical entities such as requirements, system elements, verifications, or tasks.",
     "cross_references": ["bidirectional traceability", "requirements traceability"]},
    {"term": "trade study", "page": 466,
     "definition": "An evaluation of alternatives, based on criteria and systematic analysis, to select the best alternative for attaining determined objectives."},
    {"term": "training", "page": 466,
     "definition": "Formal and informal learning options.",
     "notes": "These learning options can include classroom training, informal mentoring, web-based training, guided self study, and formalized on-the-job training programs."},

    # ── U ─────────────────────────────────────────────────────────────────
    {"term": "unit testing", "page": 466,
     "definition": "Testing of individual hardware or software units or groups of related units.",
     "cross_references": ["acceptance testing"]},

    # ── V ─────────────────────────────────────────────────────────────────
    {"term": "validation", "page": 466,
     "definition": "Confirmation that the product or service, as provided (or as it will be provided), will fulfill its intended use.",
     "cross_references": ["verification"],
     "notes": "In other words, validation ensures that 'you built the right thing.'"},
    {"term": "verification", "page": 466,
     "definition": "Confirmation that work products properly reflect the requirements specified for them.",
     "cross_references": ["validation"],
     "notes": "In other words, verification ensures that 'you built it right.'"},
    {"term": "version control", "page": 467,
     "definition": "The establishment and maintenance of baselines and the identification of changes to baselines that make it possible to return to the previous baseline.",
     "notes": "In some contexts, an individual work product may have its own baseline and a level of control less than formal configuration control may be sufficient."},

    # ── W ─────────────────────────────────────────────────────────────────
    {"term": "work breakdown structure", "abbreviation": "WBS", "page": 467,
     "definition": "An arrangement of work elements and their relationship to each other and to the end product or service."},
    {"term": "work group", "page": 467,
     "definition": "A managed set of people and other assigned resources that delivers one or more products or services to a customer or end user.",
     "cross_references": ["project"],
     "notes": "A work group can be any organizational entity with a defined purpose, whether or not that entity appears on an organization chart. Work groups can appear at any level of an organization, can contain other work groups, and can span organizational boundaries. A work group together with its work can be considered the same as a project if it has an intentionally limited lifetime."},
    {"term": "work plan", "page": 467,
     "definition": "A plan of activities and related resource allocations for a work group.",
     "notes": "Work planning includes estimating the attributes of work products and tasks, determining the resources needed, negotiating commitments, producing a schedule, and identifying and analyzing risks."},
    {"term": "work product", "page": 467,
     "definition": "A useful result of a process.",
     "cross_references": ["product", "product component"],
     "notes": "This result can include files, documents, products, parts of a product, services, process descriptions, specifications, and invoices. A key distinction between a work product and a product component is that a work product is not necessarily part of the end product. In CMMI models, the definition of 'work product' includes services, however, the phrase 'work products and services' is sometimes used to emphasize the inclusion of services in the discussion."},
    {"term": "work product and task attributes", "page": 467,
     "definition": "Characteristics of products, services, and tasks used to help in estimating work.",
     "notes": "These characteristics include items such as size, complexity, weight, form, fit, and function. They are typically used as one input to deriving other resource estimates (e.g., effort, cost, schedule)."},
    {"term": "work startup", "page": 468,
     "definition": "When a set of interrelated resources for a work group is directed to develop or deliver one or more products or services for a customer or end user.",
     "cross_references": ["work group"]},
]
