"""
D-3 Glossary verbatim data (Part 2: E-O).
"""

GLOSSARY_PART2 = [
    # ── E ─────────────────────────────────────────────────────────────────
    {"term": "end user", "page": 442,
     "definition": "A party that ultimately uses a delivered product or that receives the benefit of a delivered service.",
     "cross_references": ["customer", "service agreement", "service request"],
     "notes": "End users may or may not also be customers (who can establish and accept agreements or authorize payments). In contexts where a single service agreement covers multiple service deliveries, any party that initiates a service request can be considered an end user."},
    {"term": "enterprise", "page": 442,
     "definition": "The full composition of a company.",
     "cross_references": ["organization"],
     "notes": "A company can consist of many organizations in many locations with different customers."},
    {"term": "entry criteria", "page": 442,
     "definition": "States of being that must be present before an effort can begin successfully."},
    {"term": "equivalent staging", "page": 442,
     "definition": "A target staging, created using the continuous representation that is defined so that the results of using the target staging can be compared to maturity levels of the staged representation.",
     "cross_references": ["capability level profile", "maturity level", "target profile", "target staging"]},
    {"term": "establish and maintain", "page": 442,
     "definition": "Create, document, use, and revise work products as necessary to ensure they remain useful.",
     "notes": "The phrase 'establish and maintain' plays a special role in communicating a deeper principle in CMMI: work products that have a central or key role in work group, project, and organizational performance should be given attention to ensure they are used and useful in that role. This phrase has particular significance in CMMI because it often appears in goal and practice statements (though in the former as 'established and maintained') and should be taken as shorthand for applying the principle to whatever work product is the object of the phrase."},
    {"term": "example work product", "page": 442,
     "definition": "An informative model component that provides sample outputs from a specific practice."},
    {"term": "executive", "page": 442,
     "definition": "See senior manager.",
     "cross_references": ["senior manager"]},
    {"term": "exit criteria", "page": 443,
     "definition": "States of being that must be present before an effort can end successfully."},
    {"term": "expected CMMI components", "page": 443,
     "definition": "CMMI components that describe the activities that are important in achieving a required CMMI component.",
     "notes": "Model users can implement the expected components explicitly or implement equivalent practices to these components. Specific and generic practices are expected model components."},

    # ── F ─────────────────────────────────────────────────────────────────
    {"term": "findings", "page": 443,
     "definition": "See appraisal findings.",
     "cross_references": ["appraisal findings"]},
    {"term": "formal evaluation process", "page": 443,
     "definition": "A structured approach to evaluating alternative solutions against established criteria to determine a recommended solution to address an issue."},
    {"term": "framework", "page": 443,
     "definition": "See CMMI Framework.",
     "cross_references": ["CMMI Framework"]},
    {"term": "functional analysis", "page": 443,
     "definition": "Examination of a defined function to identify all the subfunctions necessary to accomplish that function; identification of functional relationships and interfaces (internal and external) and capturing these relationships and interfaces in a functional architecture; and flow down of upper level requirements and assignment of these requirements to lower level subfunctions.",
     "cross_references": ["functional architecture"]},
    {"term": "functional architecture", "page": 443,
     "definition": "The hierarchical arrangement of functions, their internal and external (external to the aggregation itself) functional interfaces and external physical interfaces, their respective requirements, and their design constraints.",
     "cross_references": ["architecture", "functional analysis", "definition of required functionality and quality attributes"]},

    # ── G ─────────────────────────────────────────────────────────────────
    {"term": "generic goal", "abbreviation": "GG", "page": 443,
     "definition": "A required model component that describes characteristics that must be present to institutionalize processes that implement a process area.",
     "cross_references": ["institutionalization"]},
    {"term": "generic practice", "abbreviation": "GP", "page": 443,
     "definition": "An expected model component that is considered important in achieving the associated generic goal.",
     "notes": "The generic practices associated with a generic goal describe the activities that are expected to result in achievement of the generic goal and contribute to the institutionalization of the processes associated with a process area."},
    {"term": "generic practice elaboration", "page": 443,
     "definition": "An informative model component that appears after a generic practice to provide guidance on how the generic practice could be applied uniquely to a process area.",
     "notes": "This model component is not present in all CMMI models."},

    # ── H ─────────────────────────────────────────────────────────────────
    {"term": "hardware engineering", "page": 444,
     "definition": "The application of a systematic, disciplined, and quantifiable approach to transforming a set of requirements that represent the collection of stakeholder needs, expectations, and constraints, using documented techniques and technology to design, implement, and maintain a tangible product.",
     "cross_references": ["software engineering", "systems engineering"],
     "notes": "In CMMI, hardware engineering represents all technical fields (e.g., electrical, mechanical) that transform requirements and ideas into tangible products."},
    {"term": "higher level management", "page": 444,
     "definition": "The person or persons who provide the policy and overall guidance for the process but do not provide the direct day-to-day monitoring and controlling of the process.",
     "cross_references": ["senior manager"],
     "notes": "Such persons belong to a level of management in the organization above the immediate level responsible for the process and can be (but are not necessarily) senior managers."},

    # ── I ─────────────────────────────────────────────────────────────────
    {"term": "incomplete process", "page": 444,
     "definition": "A process that is not performed or is performed only partially; one or more of the specific goals of the process area are not satisfied.",
     "notes": "An incomplete process is also known as capability level 0."},
    {"term": "informative CMMI components", "page": 444,
     "definition": "CMMI components that help model users understand the required and expected components of a model.",
     "notes": "These components can be examples, detailed explanations, or other helpful information. Subpractices, notes, references, goal titles, practice titles, sources, example work products, and generic practice elaborations are informative model components."},
    {"term": "institutionalization", "page": 444,
     "definition": "The ingrained way of doing business that an organization follows routinely as part of its corporate culture."},
    {"term": "interface control", "page": 444,
     "definition": "In configuration management, the process of (1) identifying all functional and physical characteristics relevant to the interfacing of two or more configuration items provided by one or more organizations and (2) ensuring that proposed changes to these characteristics are evaluated and approved prior to implementation.",
     "cross_references": ["configuration item", "configuration management"]},

    # ── L ─────────────────────────────────────────────────────────────────
    {"term": "lifecycle model", "page": 444,
     "definition": "A partitioning of the life of a product, service, project, work group, or set of work activities into phases."},

    # ── M ─────────────────────────────────────────────────────────────────
    {"term": "managed process", "page": 445,
     "definition": "A performed process that is planned and executed in accordance with policy; employs skilled people having adequate resources to produce controlled outputs; involves relevant stakeholders; is monitored, controlled, and reviewed; and is evaluated for adherence to its process description.",
     "cross_references": ["performed process"]},
    {"term": "manager", "page": 445,
     "definition": "A person who provides technical and administrative direction and control to those who perform tasks or activities within the manager's area of responsibility.",
     "notes": "This term has a special meaning in the CMMI Product Suite besides its common standard English meaning. The traditional functions of a manager include planning, organizing, directing, and controlling work within an area of responsibility."},
    {"term": "maturity level", "abbreviation": "ML", "page": 445,
     "definition": "Degree of process improvement across a predefined set of process areas in which all goals in the set are attained.",
     "cross_references": ["capability level", "process area"]},
    {"term": "measure (noun)", "page": 445,
     "definition": "Variable to which a value is assigned as a result of measurement.",
     "cross_references": ["base measure", "derived measure", "measurement"],
     "notes": "The definition of this term in CMMI is consistent with the definition of this term in ISO 15939."},
    {"term": "measurement", "page": 445,
     "definition": "A set of operations to determine the value of a measure.",
     "cross_references": ["measure (noun)"],
     "notes": "The definition of this term in CMMI is consistent with the definition of this term in ISO 15939."},
    {"term": "measurement result", "page": 445,
     "definition": "A value determined by performing a measurement.",
     "cross_references": ["measurement"]},
    {"term": "memorandum of agreement", "abbreviation": "MOA", "page": 445,
     "definition": "Binding document of understanding or agreement between two or more parties.",
     "notes": "A memorandum of agreement is also known as a 'memorandum of understanding.'"},

    # ── N ─────────────────────────────────────────────────────────────────
    {"term": "natural bounds", "page": 445,
     "definition": "The inherent range of variation in a process, as determined by process performance measures.",
     "cross_references": ["measure (noun)", "process performance"],
     "notes": "Natural bounds are sometimes referred to as 'voice of the process.' Techniques such as control charts, confidence intervals, and prediction intervals are used to determine whether the variation is due to common causes (i.e., the process is predictable or stable) or is due to some special cause that can and should be identified and removed."},
    {"term": "nondevelopmental item", "abbreviation": "NDI", "page": 446,
     "definition": "An item that was developed prior to its current use in an acquisition or development process.",
     "notes": "Such an item can require minor modifications to meet the requirements of its current intended use."},
    {"term": "nontechnical requirements", "page": 446,
     "definition": "Requirements affecting product and service acquisition or development that are not properties of the product or service.",
     "notes": "Examples include numbers of products or services to be delivered, data rights for delivered COTS and nondevelopmental items, delivery dates, and milestones with exit criteria. Other nontechnical requirements include work constraints associated with training, site provisions, and deployment schedules."},

    # ── O ─────────────────────────────────────────────────────────────────
    {"term": "objectively evaluate", "page": 446,
     "definition": "To review activities and work products against criteria that minimize subjectivity and bias by the reviewer.",
     "cross_references": ["audit"],
     "notes": "An example of an objective evaluation is an audit against requirements, standards, or procedures by an independent quality assurance function."},
    {"term": "operational concept", "page": 446,
     "definition": "A general description of the way in which an entity is used or operates.",
     "notes": "An operational concept is also known as 'concept of operations.'"},
    {"term": "operational scenario", "page": 446,
     "definition": "A description of an imagined sequence of events that includes the interaction of the product or service with its environment and users, as well as interaction among its product or service components.",
     "notes": "Operational scenarios are used to evaluate the requirements and design of the system and to verify and validate the system."},
    {"term": "organization", "page": 446,
     "definition": "An administrative structure in which people collectively manage one or more projects or work groups as a whole, share a senior manager, and operate under the same policies.",
     "cross_references": ["enterprise"],
     "notes": "However, the word 'organization' as used throughout CMMI models can also apply to one person who performs a function in a small organization that might be performed by a group of people in a large organization."},
    {"term": "organizational maturity", "page": 446,
     "definition": "The extent to which an organization has explicitly and consistently deployed processes that are documented, managed, measured, controlled, and continually improved.",
     "notes": "Organizational maturity can be measured via appraisals."},
    {"term": "organizational policy", "page": 447,
     "definition": "A guiding principle typically established by senior management that is adopted by an organization to influence and determine decisions."},
    {"term": "organizational process assets", "abbreviation": "OPA", "page": 447,
     "definition": "Artifacts that relate to describing, implementing, and improving processes.",
     "cross_references": ["process asset library"],
     "notes": "Examples of these artifacts include policies, measurement descriptions, process descriptions, process implementation support tools. The term 'process assets' is used to indicate that these artifacts are developed or acquired to meet the business objectives of the organization and that they represent investments by the organization that are expected to provide current and future business value."},
    {"term": "organization's business objectives", "page": 447,
     "definition": "Senior-management-developed objectives designed to ensure an organization's continued existence and enhance its profitability, market share, and other factors influencing the organization's success.",
     "cross_references": ["quality and process performance objectives", "quantitative objective"]},
    {"term": "organization's measurement repository", "page": 447,
     "definition": "A repository used to collect and make measurement results available on processes and work products, particularly as they relate to the organization's set of standard processes.",
     "notes": "This repository contains or references actual measurement results and related information needed to understand and analyze measurement results."},
    {"term": "organization's process asset library", "abbreviation": "OPAL", "page": 447,
     "definition": "A library of information used to store and make process assets available that are useful to those who are defining, implementing, and managing processes in the organization.",
     "notes": "This library contains process assets that include process related documentation such as policies, defined processes, checklists, lessons learned documents, templates, standards, procedures, plans, and training materials."},
    {"term": "organization's set of standard processes", "abbreviation": "OSSP", "page": 447,
     "definition": "A collection of definitions of the processes that guide activities in an organization.",
     "cross_references": ["defined process", "process element"],
     "notes": "These process descriptions cover the fundamental process elements (and their relationships to each other such as ordering and interfaces) that should be incorporated into the defined processes that are implemented in projects, work groups, and work across the organization. A standard process enables consistent development and maintenance activities across the organization and is essential for long-term stability and improvement."},
    {"term": "outsourcing", "page": 447,
     "definition": "See acquisition.",
     "cross_references": ["acquisition"]},
]
