"""
D-3 Glossary verbatim data (Part 1: A-D).
Extracted from CMMI-DEV V1.3, Appendix D, physical pages 433-468.
Internal use derivative work per CMU/SEI copyright notice (PDF p.2).
"""

GLOSSARY_PART1 = [
    # ── A ─────────────────────────────────────────────────────────────────
    {"term": "acceptance criteria", "page": 434,
     "definition": "The criteria that a deliverable must satisfy to be accepted by a user, customer, or other authorized entity.",
     "cross_references": ["deliverable"]},
    {"term": "acceptance testing", "page": 434,
     "definition": "Formal testing conducted to enable a user, customer, or other authorized entity to determine whether to accept a deliverable.",
     "cross_references": ["unit testing"]},
    {"term": "achievement profile", "page": 434,
     "definition": "A list of process areas and their corresponding capability levels that represent the organization's progress for each process area while advancing through the capability levels.",
     "cross_references": ["capability level profile", "target profile", "target staging"]},
    {"term": "acquirer", "page": 434,
     "definition": "The stakeholder that acquires or procures a product or service from a supplier.",
     "cross_references": ["stakeholder"]},
    {"term": "acquisition", "page": 434,
     "definition": "The process of obtaining products or services through supplier agreements.",
     "cross_references": ["supplier agreement"]},
    {"term": "acquisition strategy", "page": 434,
     "definition": "The specific approach to acquiring products and services that is based on considerations of supply sources, acquisition methods, requirements specification types, agreement types, and related acquisition risks."},
    {"term": "addition", "page": 434,
     "definition": "A clearly marked model component that contains information of interest to particular users.",
     "notes": "In a CMMI model, all additions bearing the same name can be optionally selected as a group for use. In CMMI for Services, the Service System Development (SSD) process area is an addition."},
    {"term": "allocated requirement", "page": 434,
     "definition": "Requirement that results from levying all or part of a higher level requirement on a lower level architectural element or design component.",
     "notes": "More generally, requirements can be allocated to other logical or physical components including people, consumables, delivery increments, or the architecture as a whole, depending on what best enables the product or service to achieve the requirements."},
    {"term": "appraisal", "page": 435,
     "definition": "An examination of one or more processes by a trained team of professionals using an appraisal reference model as the basis for determining, at a minimum, strengths and weaknesses.",
     "notes": "This term has a special meaning in the CMMI Product Suite besides its common standard English meaning."},
    {"term": "appraisal findings", "page": 435,
     "definition": "The results of an appraisal that identify the most important issues, problems, or opportunities for process improvement within the appraisal scope.",
     "notes": "Appraisal findings are inferences drawn from corroborated objective evidence."},
    {"term": "appraisal participants", "page": 435,
     "definition": "Members of the organizational unit who participate in providing information during an appraisal."},
    {"term": "appraisal rating", "page": 435,
     "definition": "The value assigned by an appraisal team to (a) a CMMI goal or process area, (b) the capability level of a process area, or (c) the maturity level of an organizational unit.",
     "notes": "This term is used in CMMI appraisal materials such as the SCAMPI MDD. A rating is determined by enacting the defined rating process for the appraisal method being employed."},
    {"term": "appraisal reference model", "page": 435,
     "definition": "The CMMI model to which an appraisal team correlates implemented process activities."},
    {"term": "appraisal scope", "page": 435,
     "definition": "The definition of the boundaries of an appraisal encompassing the organizational limits and CMMI model limits within which the processes to be investigated operate."},
    {"term": "architecture", "page": 435,
     "definition": "The set of structures needed to reason about a product. These structures are comprised of elements, relations among them, and properties of both.",
     "notes": "In a service context, the architecture is often applied to the service system. Note that functionality is only one aspect of the product. Quality attributes, such as responsiveness, reliability, and security, are also important to reason about.",
     "cross_references": ["functional architecture"]},
    {"term": "audit", "page": 436,
     "definition": "An objective examination of a work product or set of work products against specific criteria (e.g., requirements).",
     "cross_references": ["objectively evaluate"],
     "notes": "This is a term used in several ways in CMMI, including configuration audits and process compliance audits."},

    # ── B ─────────────────────────────────────────────────────────────────
    {"term": "baseline", "page": 436,
     "definition": "A set of specifications or work products that has been formally reviewed and agreed on, which thereafter serves as the basis for further development, and which can be changed only through change control procedures.",
     "cross_references": ["configuration baseline", "product baseline"]},
    {"term": "base measure", "page": 436,
     "definition": "Measure defined in terms of an attribute and the method for quantifying it.",
     "cross_references": ["derived measure"],
     "notes": "A base measure is functionally independent of other measures."},
    {"term": "bidirectional traceability", "page": 436,
     "definition": "An association among two or more logical entities that is discernable in either direction (i.e., to and from an entity).",
     "cross_references": ["requirements traceability", "traceability"]},
    {"term": "business objectives", "page": 436,
     "definition": "See organization's business objectives.",
     "cross_references": ["organization's business objectives"]},

    # ── C ─────────────────────────────────────────────────────────────────
    {"term": "capability level", "abbreviation": "CL", "page": 436,
     "definition": "Achievement of process improvement within an individual process area.",
     "cross_references": ["generic goal", "specific goal", "maturity level", "process area"],
     "notes": "A capability level is defined by appropriate specific and generic goals for a process area."},
    {"term": "capability level profile", "page": 436,
     "definition": "A list of process areas and their corresponding capability levels.",
     "cross_references": ["achievement profile", "target profile", "target staging"],
     "notes": "A capability level profile can be an 'achievement profile' when it represents the organization's progress for each process area while advancing through the capability levels. Or, it can be a 'target profile' when it represents an objective for process improvement."},
    {"term": "capability maturity model", "abbreviation": "CMM", "page": 436,
     "definition": "A model that contains the essential elements of effective processes for one or more areas of interest and describes an evolutionary improvement path from ad hoc, immature processes to disciplined, mature processes with improved quality and effectiveness."},
    {"term": "capable process", "page": 436,
     "definition": "A process that can satisfy its specified product quality, service quality, and process performance objectives.",
     "cross_references": ["stable process", "standard process"]},
    {"term": "causal analysis", "page": 436,
     "definition": "The analysis of outcomes to determine their causes."},
    {"term": "change management", "page": 437,
     "definition": "Judicious use of means to effect a change, or a proposed change, to a product or service.",
     "cross_references": ["configuration management"]},
    {"term": "CMMI Framework", "page": 437,
     "definition": "The basic structure that organizes CMMI components, including elements of current CMMI models as well as rules and methods for generating models, appraisal methods (including associated artifacts), and training materials.",
     "cross_references": ["CMMI model", "CMMI Product Suite"],
     "notes": "The framework enables new areas of interest to be added to CMMI so that they will integrate with the existing ones."},
    {"term": "CMMI model", "page": 437,
     "definition": "A model generated from the CMMI Framework.",
     "cross_references": ["CMMI Framework", "CMMI Product Suite"]},
    {"term": "CMMI model component", "page": 437,
     "definition": "Any of the main architectural elements that compose a CMMI model.",
     "notes": "Some of the main elements of a CMMI model include specific practices, generic practices, specific goals, generic goals, process areas, capability levels, and maturity levels."},
    {"term": "CMMI Product Suite", "page": 437,
     "definition": "The complete set of products developed around the CMMI concept.",
     "cross_references": ["CMMI Framework", "CMMI model"],
     "notes": "These products include the framework itself, models, appraisal methods, appraisal materials, and training materials."},
    {"term": "commercial off-the-shelf", "abbreviation": "COTS", "page": 437,
     "definition": "Items that can be purchased from a commercial supplier."},
    {"term": "common cause of variation", "page": 437,
     "definition": "The variation of a process that exists because of normal and expected interactions among components of a process.",
     "cross_references": ["special cause of variation"]},
    {"term": "configuration audit", "page": 437,
     "definition": "An audit conducted to verify that a configuration item or a collection of configuration items that make up a baseline conforms to a specified standard or requirement.",
     "cross_references": ["audit", "configuration item"]},
    {"term": "configuration baseline", "page": 437,
     "definition": "The configuration information formally designated at a specific time during a product's or product component's life.",
     "cross_references": ["product lifecycle"],
     "notes": "Configuration baselines plus approved changes from those baselines constitute the current configuration information."},
    {"term": "configuration control", "page": 438,
     "definition": "An element of configuration management consisting of the evaluation, coordination, approval or disapproval, and implementation of changes to configuration items after formal establishment of their configuration identification.",
     "cross_references": ["configuration identification", "configuration item", "configuration management"]},
    {"term": "configuration control board", "abbreviation": "CCB", "page": 438,
     "definition": "A group of people responsible for evaluating and approving or disapproving proposed changes to configuration items and for ensuring implementation of approved changes.",
     "cross_references": ["configuration item"],
     "notes": "Configuration control boards are also known as 'change control boards.'"},
    {"term": "configuration identification", "page": 438,
     "definition": "An element of configuration management consisting of selecting the configuration items for a product, assigning unique identifiers to them, and recording their functional and physical characteristics in technical documentation.",
     "cross_references": ["configuration item", "configuration management", "product"]},
    {"term": "configuration item", "abbreviation": "CI", "page": 438,
     "definition": "An aggregation of work products that is designated for configuration management and treated as a single entity in the configuration management process.",
     "cross_references": ["configuration management"]},
    {"term": "configuration management", "abbreviation": "CM", "page": 438,
     "definition": "A discipline applying technical and administrative direction and surveillance to (1) identify and document the functional and physical characteristics of a configuration item, (2) control changes to those characteristics, (3) record and report change processing and implementation status, and (4) verify compliance with specified requirements.",
     "cross_references": ["configuration audit", "configuration control", "configuration identification", "configuration status accounting"]},
    {"term": "configuration status accounting", "page": 438,
     "definition": "An element of configuration management consisting of the recording and reporting of information needed to manage a configuration effectively.",
     "cross_references": ["configuration identification", "configuration management"],
     "notes": "This information includes a list of the approved configuration, the status of proposed changes to the configuration, and the implementation status of approved changes."},
    {"term": "constellation", "page": 438,
     "definition": "A collection of CMMI components that are used to construct models, training materials, and appraisal related documents for an area of interest (e.g., acquisition, development, services)."},
    {"term": "continuous representation", "page": 439,
     "definition": "A capability maturity model structure wherein capability levels provide a recommended order for approaching process improvement within each specified process area.",
     "cross_references": ["capability level", "process area", "staged representation"]},
    {"term": "contractor", "page": 439,
     "definition": "See supplier.",
     "cross_references": ["supplier"]},
    {"term": "contractual requirements", "page": 439,
     "definition": "The result of the analysis and refinement of customer requirements into a set of requirements suitable to be included in one or more solicitation packages, or supplier agreements.",
     "cross_references": ["acquirer", "customer requirement", "supplier agreement", "solicitation package"],
     "notes": "Contractual requirements include both technical and nontechnical requirements necessary for the acquisition of a product or service."},
    {"term": "corrective action", "page": 439,
     "definition": "Acts or deeds used to remedy a situation or remove an error."},
    {"term": "customer", "page": 439,
     "definition": "The party responsible for accepting the product or for authorizing payment.",
     "cross_references": ["stakeholder", "customer requirement", "end user"],
     "notes": "The customer is external to the project or work group (except possibly in certain project structures in which the customer effectively is on the project team or in the work group) but not necessarily external to the organization. The customer can be a higher level project or work group. Customers are a subset of stakeholders. In most cases where this term is used, the preceding definition is intended; however, in some contexts, the term 'customer' is intended to include other relevant stakeholders. End users can be distinguished from customers if the parties that directly receive the value of products and services are not the same as the parties that arrange for, pay for, or negotiate agreements."},
    {"term": "customer requirement", "page": 439,
     "definition": "The result of eliciting, consolidating, and resolving conflicts among the needs, expectations, constraints, and interfaces of the product's relevant stakeholders in a way that is acceptable to the customer.",
     "cross_references": ["customer"]},

    # ── D ─────────────────────────────────────────────────────────────────
    {"term": "data", "page": 439,
     "definition": "Recorded information.",
     "notes": "Recorded information can include technical data, computer software documents, financial information, management information, representation of facts, numbers, or datum of any nature that can be communicated, stored, and processed."},
    {"term": "data management", "page": 440,
     "definition": "The disciplined processes and systems that plan for, acquire, and provide stewardship for business and technical data, consistent with data requirements, throughout the data lifecycle."},
    {"term": "defect density", "page": 440,
     "definition": "Number of defects per unit of product size.",
     "notes": "An example is the number of problem reports per thousand lines of code."},
    {"term": "defined process", "page": 440,
     "definition": "A managed process that is tailored from the organization's set of standard processes according to the organization's tailoring guidelines; has a maintained process description; and contributes process related experiences to the organizational process assets.",
     "cross_references": ["managed process"]},
    {"term": "definition of required functionality and quality attributes", "page": 440,
     "definition": "A characterization of required functionality and quality attributes obtained through 'chunking,' organizing, annotating, structuring, or formalizing the requirements (functional and non-functional) to facilitate further refinement and reasoning about the requirements as well as (possibly, initial) solution exploration, definition, and evaluation.",
     "cross_references": ["architecture", "functional architecture", "quality attribute"]},
    {"term": "deliverable", "page": 440,
     "definition": "An item to be provided to an acquirer or other designated recipient as specified in an agreement.",
     "cross_references": ["acquirer"],
     "notes": "This item can be a document, hardware item, software item, service, or any type of work product."},
    {"term": "delivery environment", "page": 441,
     "definition": "The complete set of circumstances and conditions under which services are delivered in accordance with service agreements.",
     "cross_references": ["service", "service agreement"]},
    {"term": "derived measure", "page": 441,
     "definition": "Measure that is defined as a function of two or more values of base measures.",
     "cross_references": ["base measure"]},
    {"term": "derived requirements", "page": 441,
     "definition": "Requirements that are not explicitly stated in customer requirements but are inferred (1) from contextual requirements (e.g., applicable standards, laws, policies, common practices, management decisions) or (2) from requirements needed to specify a product or service component.",
     "cross_references": ["product requirements"]},
    {"term": "design review", "page": 441,
     "definition": "A formal, documented, comprehensive, and systematic examination of a design to determine if the design meets the applicable requirements, to identify problems, and to propose solutions."},
    {"term": "development", "page": 441,
     "definition": "To create a product or service system by deliberate effort.",
     "notes": "In some contexts, development can include the maintenance of the developed product."},
    {"term": "document", "page": 441,
     "definition": "A collection of data, regardless of the medium on which it is recorded, that generally has permanence and can be read by humans or machines.",
     "notes": "Documents include both paper and electronic documents."},
]
